version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_5435
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: message_user
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: storage_message
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_5050
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: "123456"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:


# Email: admin@example.com
# Password: 123456
